//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADASO_AgreementApp.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maill
    {
        public string Name { get; set; }
        public string Surname { get; set; }
        public string MailAdress { get; set; }
        public string PhoneNumber { get; set; }
        public int MId { get; set; }
        public int AId { get; set; }
        public IEnumerable<Maill> MailList { get; set; }

        public virtual Agreementt Agreementt { get; set; }
    }
}
